In [1]:
import numpy as np
import tensorflow as tf

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
from sklearn.datasets import fetch_california_housing

In [14]:
housing = fetch_california_housing()
m, n = housing.data.shape

In [17]:
housing

{'DESCR': 'California housing dataset.\n\nThe original database is available from StatLib\n\n    http://lib.stat.cmu.edu/datasets/\n\nThe data contains 20,640 observations on 9 variables.\n\nThis dataset contains the average house value as target variable\nand the following input variables (features): average income,\nhousing average age, average rooms, average bedrooms, population,\naverage occupation, latitude, and longitude in that order.\n\nReferences\n----------\n\nPace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\nStatistics and Probability Letters, 33 (1997) 291-297.\n\n',
 'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.     

In [4]:
housing_data_plus_bias = np.c_[np.ones((m, 1)), housing.data]

In [8]:
X = tf.constant(
    housing_data_plus_bias, 
    dtype = tf.float32,
    name = "X"
)

y = tf.constant(
    housing.target.reshape(-1, 1),
    dtype = tf.float32,
    name = "y"
)

XT = tf.transpose(X)

theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT, X)), XT), y)

In [10]:
with tf.Session() as sess:
    theta_value = theta.eval()

In [13]:
theta_value.round(1)

array([[-37.2],
       [  0.4],
       [  0. ],
       [ -0.1],
       [  0.6],
       [ -0. ],
       [ -0. ],
       [ -0.4],
       [ -0.4]], dtype=float32)

In [38]:
predictions = []
for i in np.arange(100):
    row = housing.data[:i,:]
    predictions.append(theta_value[:1] + row.dot(theta_value[1:9]))

[array([], shape=(0, 1), dtype=float64),
 array([[4.13342837]]),
 array([[4.13342837],
        [3.97895735]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575],
        [3.24373375]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575],
        [3.24373375],
        [2.41645462]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575],
        [3.24373375],
        [2.41645462],
        [2.6777611 ]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575],
        [3.24373375],
        [2.41645462],
        [2.6777611 ],
        [2.39807253]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575],
        [3.24373375],
        [2.41645462],
        [2.6777611 ],
        [2.39807253],
        [2.24949391]]),
 array([[4.13342837],
        [3.97895735],
        [3.67862575],
        [3.24373375],
        [2.41645462],
        [2.6777611 ],
        [2.39807253