# TensorFlow Basics

In [4]:
import tensorflow as tf

In [35]:
# Make sure you are using 1.3 for exact sytnax matching!
print(tf.__version__)

1.8.0


## Tensors

In [6]:
hello = tf.constant('Hello')

In [7]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [8]:
world = tf.constant('World')

In [9]:
result = hello + world

In [10]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [11]:
type(result)

tensorflow.python.framework.ops.Tensor

In [12]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [13]:
result

b'HelloWorld'

** Computations **

In [14]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [15]:
type(tensor_1)

tensorflow.python.framework.ops.Tensor

In [16]:
tensor_1 + tensor_2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [17]:
sess

In [18]:
sess.close()

## Operations

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)

In [24]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [25]:
my_ops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

## Interactive Session

Useful for Notebook Sessions

In [26]:
# Only run this cell once!
sess = tf.InteractiveSession()

In [27]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.5951016  -0.26722434  0.19814904  0.6422067 ]
 [-1.0850554  -1.0060767  -0.42399654 -0.50104654]
 [-0.7413445  -0.15482104 -0.05080614  0.48630476]
 [ 0.07147641 -0.29361802 -0.18306653  0.4358574 ]]


[[0.27135503 0.56760836 0.25981343 0.9773375 ]
 [0.6751392  0.01864612 0.12004483 0.5126214 ]
 [0.28793395 0.34636855 0.22167063 0.31726706]
 [0.04536879 0.6376294  0.40141642 0.82453275]]




## Matrix Multiplication

In [28]:
a = tf.constant([ [1,2],
                  [3,4] ])

In [29]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [30]:
b = tf.constant([[10],[100]])

In [31]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [32]:
result = tf.matmul(a,b)

In [33]:
result.eval()

array([[210],
       [430]], dtype=int32)