# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[45, 66],
       [14, 57],
       [97, 46],
       [78, 73],
       [65, 92],
       [39, 70],
       [92, 78],
       [93, 72],
       [12, 37],
       [18, 79]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scaler_model.transform(data)

array([[0.38823529, 0.52727273],
       [0.02352941, 0.36363636],
       [1.        , 0.16363636],
       [0.77647059, 0.65454545],
       [0.62352941, 1.        ],
       [0.31764706, 0.6       ],
       [0.94117647, 0.74545455],
       [0.95294118, 0.63636364],
       [0.        , 0.        ],
       [0.07058824, 0.76363636]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
result

array([[0.38823529, 0.52727273],
       [0.02352941, 0.36363636],
       [1.        , 0.16363636],
       [0.77647059, 0.65454545],
       [0.62352941, 1.        ],
       [0.31764706, 0.6       ],
       [0.94117647, 0.74545455],
       [0.95294118, 0.63636364],
       [0.        , 0.        ],
       [0.07058824, 0.76363636]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0  52   6  61     32
1   1  94  14     68
2  44  70  44     94
3  51  93  40     14
4  33   5  97     53

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

## Great Job!